name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with PUBLIC_URL
        run: |
          docker build --build-arg PUBLIC_URL=${{ secrets.PUBLIC_URL }} -t react-app .

      - name: Save Docker image to tar
        run: |
          docker save react-app | gzip > react-app.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'react-app.tar.gz'
          target: '/home/${{ secrets.SSH_USER }}'

      - name: Run docker container on server with PUBLIC_URL
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load < ~/react-app.tar.gz
            docker stop react-app || true
            docker rm react-app || true
            docker run -d \
              --name react-app \
              -e PUBLIC_URL=${{ secrets.PUBLIC_URL }} \
              -p 3015:80 \
              react-app
