name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      dist-path: ${{ steps.upload.outputs.artifact-path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install --force

      - name: Build React app
        run: npm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-dist
          path: |
            dist
            nginx.conf.template

  docker-and-deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      PUBLIC_URL: ${{ secrets.PUBLIC_URL }}

    steps:
      - name: Checkout code (for Dockerfile)
        uses: actions/checkout@v4

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: react-dist
          path: ./dist-artifact

      - name: Copy dist to build context
        run: |
          cp -r ./dist-artifact/dist ./dist
          cp ./dist-artifact/nginx.conf.template ./nginx.conf.template

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PUBLIC_URL=$PUBLIC_URL \
            -t react-app .

      - name: Save Docker image to tar.gz
        run: docker save react-app | gzip > react-app.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'react-app.tar.gz'
          target: '/home/${{ secrets.SSH_USER }}'

      - name: Deploy container on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load < ~/react-app.tar.gz
            docker stop react-app || true
            docker rm react-app || true
            docker run -d \
              --name react-app \
              -e PUBLIC_URL=${{ secrets.PUBLIC_URL }} \
              -p 3015:80 \
              react-app
